### ISSUE TITLE
[solved] fill_er_up: undefined method `my_zone' for nil:NilClass

### ISSUE THREAD

**Issue by cben** [zeari/miq-helpers#12]
It's silly opening an issue just to close it, but I wasted a hour on this and want to dump the findings quickly...
Immediately after a DB reset, fill_er_up fails with:

```
/home/bpaskinc/miq/events/app/models/miq_server.rb:560:in `my_zone': undefined method `my_zone' for nil:NilClass (NoMethodError)
    from /home/bpaskinc/miq/events/app/models/zone.rb:86:in `determine_queue_zone'
    from /home/bpaskinc/miq/events/app/models/miq_queue.rb:113:in `put'
    from /home/bpaskinc/miq/events/app/models/miq_event.rb:108:in `raise_evm_event_queue'
    from /home/bpaskinc/miq/events/app/models/authentication.rb:75:in `raise_event'
    from /home/bpaskinc/miq/events/app/models/authentication.rb:89:in `after_authentication_changed'
...
```

This affects the old fill_er_up.sh, the new fill_er_up.rb and even @yaacov's [set-miq-providers.rb](https://github.com/yaacov/miq-scripts/blob/master/set-miq-providers.rb).

=> Turns out **you must simply launch ManageIQ at least once before running fill_er_up.**  Then the Zone and MiqServer tables won't be empty (as they are immediately after DB reset) and it will succeed.

**Comment by zeari** [comment]
Well yeah, its meant to fill a running system.
You can either run miq or run rake db:seed

**Comment by cben** [comment]
Wait, evm:db:reset alone doesn't seed?
I suppose I knew this, once upon a time.  :flushed:  Thanks!
